package model;

import java.sql.Timestamp;

/**
 * Model cho User entity - tương ứng với bảng "User" trong database
 */
public class User {
    // Primary Key
    private Integer userID;
    
    // Basic Info
    private String userName;
    private String email;
    private String passwordHash;
    private String fullName;
    private String phoneNumber;
    private String address;
    private String status;
    
    // Foreign Keys
    private Integer roleSettingID;
    private String roleSettingName;
    private Integer shopID;
    
    // Timestamps (auto-generated by database)
    private Timestamp createdAt;
    private Timestamp updatedAt;
    
    // Constructors
    public User() {
        this.status = "Active"; // Default status
    }

    public User(Integer userID, String userName, String email, String passwordHash, String fullName, String phoneNumber, String address, String status, Integer roleSettingID, String roleSettingName, Integer shopID, Timestamp createdAt, Timestamp updatedAt) {
        this.userID = userID;
        this.userName = userName;
        this.email = email;
        this.passwordHash = passwordHash;
        this.fullName = fullName;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.status = status;
        this.roleSettingID = roleSettingID;
        this.roleSettingName = roleSettingName;
        this.shopID = shopID;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    
    public User(String userName, String email, String passwordHash, String fullName) {
        this.userName = userName;
        this.email = email;
        this.passwordHash = passwordHash;
        this.fullName = fullName;
        this.status = "Active";
    }
    
    public User(String userName, String email, String passwordHash, String fullName, 
                String phoneNumber, String address) {
        this.userName = userName;
        this.email = email;
        this.passwordHash = passwordHash;
        this.fullName = fullName;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.status = "Active";
    }
    
    // Getters and Setters
    public Integer getUserID() {
        return userID;
    }
    
    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    public String getRoleSettingName() {
        return roleSettingName;
    }

    public void setRoleSettingName(String roleSettingName) {
        this.roleSettingName = roleSettingName;
    }
    
    public String getUserName() {
        return userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    public String getEmail() {
        return email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    public String getPasswordHash() {
        return passwordHash;
    }
    
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
    
    public String getFullName() {
        return fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    
    public String getPhoneNumber() {
        return phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
    public String getAddress() {
        return address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public Integer getRoleSettingID() {
        return roleSettingID;
    }
    
    public void setRoleSettingID(Integer roleSettingID) {
        this.roleSettingID = roleSettingID;
    }
    
    public Integer getShopID() {
        return shopID;
    }
    
    public void setShopID(Integer shopID) {
        this.shopID = shopID;
    }
    
    public Timestamp getCreatedAt() {
        return createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }
    
    public Timestamp getUpdatedAt() {
        return updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }
    
    // Compatibility methods for old LoginServices (deprecated, để backward compatibility)
    @Deprecated
    public String getUserId() {
        return userID != null ? userID.toString() : null;
    }
    
    @Deprecated
    public void setUserId(String userId) {
        this.userID = userId != null ? Integer.parseInt(userId) : null;
    }
    
    @Deprecated
    public String getUsername() {
        return userName;
    }
    
    @Deprecated
    public void setUsername(String username) {
        this.userName = username;
    }
    
    @Deprecated
    public String getPassword() {
        return passwordHash;
    }
    
    @Deprecated
    public void setPassword(String password) {
        this.passwordHash = password;
    }
    
    @Deprecated
    public String getPhone() {
        return phoneNumber;
    }
    
    @Deprecated
    public void setPhone(String phone) {
        this.phoneNumber = phone;
    }
    
    @Deprecated
    public String getRole() {
        // Cần implement method để lấy role từ Setting table
        // Tạm thời return null, sẽ cần join với Setting table
        return null;
    }
    
    @Deprecated
    public void setRole(String role) {
        // Cần implement method để set role thông qua Setting table
        // Tạm thời không làm gì
    }
    
    // Utility methods
    @Override
    public String toString() {
        return "User{" +
                "userID=" + userID +
                ", userName='" + userName + '\'' +
                ", email='" + email + '\'' +
                ", fullName='" + fullName + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", address='" + address + '\'' +
                ", status='" + status + '\'' +
                ", roleSettingID=" + roleSettingID +
                ", shopID=" + shopID +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
    
    /**
     * Kiểm tra user có active không
     * @return true nếu status là 'Active'
     */
    public boolean isActive() {
        return "Active".equalsIgnoreCase(this.status);
    }
    
    /**
     * Kiểm tra user có thuộc shop nào không
     * @return true nếu có shopID
     */
    public boolean hasShop() {
        return this.shopID != null && this.shopID > 0;
    }
    
    /**
     * Kiểm tra user có role setting không
     * @return true nếu có roleSettingID
     */
    public boolean hasRole() {
        return this.roleSettingID != null && this.roleSettingID > 0;
    }
    
    /**
     * Kiểm tra thông tin cơ bản có đầy đủ không
     * @return true nếu có đủ userName, email, passwordHash
     */
    public boolean isValidForRegistration() {
        return userName != null && !userName.trim().isEmpty() &&
               email != null && !email.trim().isEmpty() &&
               passwordHash != null && !passwordHash.trim().isEmpty();
    }
    
    /**
     * Tạo display name từ fullName hoặc userName
     * @return Display name
     */
    public String getDisplayName() {
        if (fullName != null && !fullName.trim().isEmpty()) {
            return fullName;
        }
        return userName;
    }
}